### ISSUE TITLE
Ethics Team - May Update

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#32]
- [x] onboard Erin
- [ ] onboard Angela 
- [x] Erin mtg 1 discuss plans
- [ ] Erin mtg 2 prep deliverable / presentations
- [ ] @balicea discuss Data/Privacy event
- [ ] Erin - Github account
- [ ] shared notes: decide gmail vs notion 
- [x] create notion database 
- [ ] put notion databse in online/shared / open format
